name: workshop_env
channels:
- rdkit
- conda-forge
dependencies:
- pip
- numpy
- ipython
- jupyter
- matplotlib
- numpy
- pandas
- scipy
- seaborn
- tqdm
- rdkit
- scikit-learn
- pip:
  - tensorflow
  - tensorflow-probability
  - dm-sonnet
  - graph_nets
  - umap-learn
  - littleballoffur
  - ogb
